server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: approval-service
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
