---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip
    - git
    - docker-compose-plugin
  tags: [packages, docker]

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  tags: [docker]

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  tags: [docker]

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  tags: [docker]

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags: [docker]

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  tags: [docker]

- name: Clone Beeploy repository
  git:
    repo: "{{ beeploy_repo_url | default('https://github.com/wronai/beepload.git') }}"
    dest: "{{ beeploy_install_dir | default('/opt/beepload') }}"
    version: "{{ beeploy_version | default('main') }}"
    force: yes
  tags: [deploy]

- name: Copy .env file
  template:
    src: env.j2
    dest: "{{ beeploy_install_dir | default('/opt/beepload') }}/.env"
  when: beeploy_env is defined
  tags: [config]

- name: Start Beepload services
  command: docker-compose up -d
  args:
    chdir: "{{ beeploy_install_dir | default('/opt/beepload') }}"
  tags: [deploy]

- name: Wait for services to be ready
  wait_for:
    port: "{{ item }}"
    timeout: 30
  loop: "{{ beeploy_ports | default([80, 443, 3000]) }}"
  tags: [deploy]
